# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=50),
        ),
    ]
