# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=50),
        ),
    ]
