# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'images')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
