# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(default=b'user1.jpg', upload_to=b'photos'),
        ),
    ]
